[build]
  command = "npx xertz@0.54.0"
  publish = "_dist"

[[redirects]]
  from = "http://frosty-benz-141b70.netlify.com/*"
  to = "https://www.geekytidbits.com/:splat"
  force = true
[[redirects]]
  from = "https://frosty-benz-141b70.netlify.com/*"
  to = "https://www.geekytidbits.com/:splat"
  force = true
[[redirects]]
  from = "/feed"
  to = "/rss.xml"
  force = true
[[redirects]]
  from = "/feed/index.xml"
  to = "/rss.xml"
  force = true

# For Kayla
[[redirects]]
  from = "/saturn"
  to = "https://sites.google.com/view/kayla-saturn-adventure"
